app-id: io.github.tsmetana.mpk3-settings
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
finish-args:
# show windows with Wayland
  - --socket=wayland
# show windows using X11, if Wayland is not available
  - --socket=fallback-x11
# share IPC namespace with the host (necessary for X11)
  - --share=ipc
# Midi
  - --device=all
command: mpk3-settings
cleanup:
  - /include
  - '*.a'
  - '*.la'
modules:
  - name: mpk3-settings
    buildsystem: autotools
    sources:
    - type: git
      url: https://github.com/tsmetana/mpk3-settings
#      tag: v0.1.1
      commit: 00f407e91f156dac34f87d8e86d6716a6e2d1de6
    - type: shell
      commands:
      - "autoreconf -i"
    modules:
    - name: rtmidi
      buildsystem: cmake-ninja
      sources:
      - type: git
        url: https://github.com/thestk/rtmidi
        tag: 6.0.0
        commit: 1e5b49925aa60065db52de44c366d446a902547b
